class TaskEvent:
    sent = 'sent'
    received = 'received'
    started = 'started'
    succeeded = 'succeeded'
    container_started = 'container_started'
    container_finished = 'container_finished'
    container_killed = 'container_killed'
    failed = 'failed'
    retried = 'retried'
    revoked = 'revoked'
