"""add offliner model

Revision ID: 0607dff50f80
Revises: 12096716adfd
Create Date: 2025-09-26 10:17:05.551330

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0607dff50f80"
down_revision = "12096716adfd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offliner",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("base_model", sa.String(), nullable=False),
        sa.Column("docker_image_name", sa.String(), nullable=False),
        sa.Column("command_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offliner")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offliner")
    # ### end Alembic commands ###
