"""snapshot of teams on tasks

Revision ID: 0879c4b14961
Revises: 17b1e377adfa
Create Date: 2026-10-03 09:00:39.153897

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0879c4b14961"
down_revision = "17b1e377adfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requested_task",
        sa.Column(
            "team_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False
        ),
    )
    op.create_index(
        "ix_requested_task_team_ids",
        "requested_task",
        ["team_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "task",
        sa.Column(
            "team_ids", postgresql.ARRAY(sa.Uuid()), server_default="{}", nullable=False
        ),
    )
    op.create_index(
        "ix_task_team_ids", "task", ["team_ids"], unique=False, postgresql_using="gin"
    )

    # Every recipe currently belongs to the single 'Kiwix' team, so seed all existing
    # rows with it. This also recovers tasks whose recipe has already been deleted.
    bind = op.get_bind()
    kiwix_id = bind.execute(
        sa.text("SELECT id FROM team WHERE name = 'Kiwix'")
    ).scalar_one_or_none()
    if kiwix_id is not None:
        bind.execute(
            sa.text("UPDATE task SET team_ids = ARRAY[CAST(:team_id AS uuid)]"),
            {"team_id": kiwix_id},
        )
        bind.execute(
            sa.text(
                "UPDATE requested_task SET team_ids = ARRAY[CAST(:team_id AS uuid)]"
            ),
            {"team_id": kiwix_id},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_team_ids", table_name="task", postgresql_using="gin")
    op.drop_column("task", "team_ids")
    op.drop_index(
        "ix_requested_task_team_ids",
        table_name="requested_task",
        postgresql_using="gin",
    )
    op.drop_column("requested_task", "team_ids")
    # ### end Alembic commands ###
