"""drop user email column

Revision ID: 0da404081fdf
Revises: 6dcfce58220a
Create Date: 2026-02-26 11:09:09.605815

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0da404081fdf"
down_revision = "6dcfce58220a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
