"""add recipes to teams

Revision ID: 17b1e377adfa
Revises: 79e20075be3a
Create Date: 2026-09-28 10:04:38.484420

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "17b1e377adfa"
down_revision = "79e20075be3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_private", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
    )
    op.create_index(op.f("ix_team_name"), "team", ["name"], unique=True)
    op.create_table(
        "team_history",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_private", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["account.id"],
            name=op.f("fk_team_history_author_id_account"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
            name=op.f("fk_team_history_team_id_team"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_history")),
    )
    op.create_table(
        "team_permission",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_team_permission_account_id_account"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
            name=op.f("fk_team_permission_team_id_team"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "team_id", "account_id", name=op.f("pk_team_permission")
        ),
    )
    op.create_table(
        "team_recipe",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipe.id"], name=op.f("fk_team_recipe_recipe_id_recipe")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_team_recipe_team_id_team")
        ),
        sa.PrimaryKeyConstraint("recipe_id", "team_id", name=op.f("pk_team_recipe")),
    )
    op.add_column(
        "recipe_history",
        sa.Column(
            "teams",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    bind = op.get_bind()

    team_id = bind.execute(
        sa.text(
            """
            INSERT INTO team (name, is_private)
            VALUES ('Kiwix', FALSE)
            RETURNING id
            """
        )
    ).scalar_one()

    author_id = bind.execute(
        sa.text("SELECT id FROM account WHERE username = 'maint-scripts'")
    ).scalar_one()

    # Record the team creation in its history
    bind.execute(
        sa.text(
            """
            INSERT INTO team_history (team_id, author_id, comment, name, is_private)
            VALUES (:team_id, :author_id, 'Team created', 'Kiwix', FALSE)
            """
        ),
        {"team_id": team_id, "author_id": author_id},
    )
    # Associate every recipe with the team
    bind.execute(
        sa.text(
            """
            INSERT INTO team_recipe (team_id, recipe_id)
            SELECT CAST(:team_id AS uuid), recipe.id
            FROM recipe
            """
        ),
        {"team_id": team_id},
    )
    # Snapshot each recipe (now including its team) into its history
    bind.execute(
        sa.text(
            """
            INSERT INTO recipe_history (
                recipe_id,
                author_id,
                created_at,
                comment,
                name,
                config,
                enabled,
                language_code,
                tags,
                periodicity,
                offliner_definition_version,
                context,
                archived,
                notification,
                teams
            )
            SELECT
                recipe.id,
                CAST(:author_id AS uuid),
                now(),
                'Recipe attached to Kiwix team',
                recipe.name,
                recipe.config,
                recipe.enabled,
                recipe.language_code,
                recipe.tags,
                recipe.periodicity,
                offliner_definition.version,
                recipe.context,
                recipe.archived,
                recipe.notification,
                jsonb_build_array(
                    jsonb_build_object(
                        'name', 'Kiwix',
                        'is_private', FALSE
                    )
                )
            FROM recipe
            JOIN offliner_definition
                ON offliner_definition.id = recipe.offliner_definition_id
            """
        ),
        {"author_id": author_id},
    )

    op.execute("""
        UPDATE account
        SET role = 'public-viewer'
        WHERE role = 'viewer'
    """)

    op.execute("""
        UPDATE account
        SET role = 'global-editor'
        WHERE role = 'editor'
    """)
    op.execute("""
        UPDATE account
        SET role = 'global-editor-requester'
        WHERE role = 'editor-requester'
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM recipe_history
        WHERE comment = 'Recipe attached to Kiwix team'
        """
    )
    op.drop_table("team_recipe")
    op.drop_table("team_permission")
    op.drop_table("team_history")
    op.drop_index(op.f("ix_team_name"), table_name="team")
    op.drop_table("team")
    op.drop_column("recipe_history", "teams")

    op.execute("""
        UPDATE account
        SET role = 'viewer'
        WHERE role IN ('public-viewer', 'global-viewer')
    """)

    op.execute("""
        UPDATE account
        SET role = 'editor'
        WHERE role IN ('team-editor', 'global-editor')
    """)

    op.execute("""
        UPDATE account
        SET role = 'editor-requester'
        WHERE role IN ('team-editor-requester', 'global-editor-requester')
    """)
    # ### end Alembic commands ###
