"""add tags to schedules and workers

Revision ID: 1aaef11983e7
Revises: ceae21f592b7
Create Date: 2025-08-21 15:47:09.514000

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1aaef11983e7"
down_revision = "5591af334874"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requested_task",
        sa.Column("context", sa.String(), nullable=False, server_default=""),
    )
    op.add_column(
        "schedule", sa.Column("context", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "task", sa.Column("context", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "worker",
        sa.Column(
            "contexts",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker", "contexts")
    op.drop_column("schedule", "context")
    op.drop_column("requested_task", "context")
    op.drop_column("task", "context")
    # ### end Alembic commands ###
