"""make blob schedule nullable

Revision ID: 1c8337800485
Revises: e05f7a3a524d
Create Date: 2025-12-12 12:59:35.460194

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c8337800485"
down_revision = "e05f7a3a524d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blob", "schedule_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("fk_blob_schedule_id_schedule", "blob", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_blob_schedule_id_schedule"),
        "blob",
        "schedule",
        ["schedule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_blob_schedule_id_schedule"), "blob", type_="foreignkey")
    op.create_foreign_key(
        "fk_blob_schedule_id_schedule",
        "blob",
        "schedule",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("blob", "schedule_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
