"""add comments to blobs

Revision ID: 33aa007735da
Revises: 1c8337800485
Create Date: 2025-12-19 12:18:17.418194

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33aa007735da"
down_revision = "1c8337800485"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blob", sa.Column("comments", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blob", "comments")
    # ### end Alembic commands ###
