"""create task file model


Revision ID: 33aea27bb96e
Revises: c1716b0a1595
Create Date: 2025-11-06 16:07:21.385887

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "33aea27bb96e"
down_revision = "c1716b0a1595"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("cms_status_code", sa.Integer(), nullable=True),
        sa.Column("cms_succeeded", sa.Boolean(), nullable=True),
        sa.Column("cms_on", sa.DateTime(), nullable=True),
        sa.Column("cms_book_id", sa.Uuid(), nullable=True),
        sa.Column("cms_title_ident", sa.String(), nullable=True),
        sa.Column("cms_notified", sa.Boolean(), nullable=True),
        sa.Column("created_timestamp", sa.DateTime(), nullable=True),
        sa.Column("uploaded_timestamp", sa.DateTime(), nullable=True),
        sa.Column("failed_timestamp", sa.DateTime(), nullable=True),
        sa.Column("check_timestamp", sa.DateTime(), nullable=True),
        sa.Column("check_result", sa.Integer(), nullable=True),
        sa.Column("check_log", sa.String(), nullable=True),
        sa.Column(
            "check_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "info",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["task.id"], name=op.f("fk_file_task_id_task")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file")),
        sa.UniqueConstraint("task_id", "name", name=op.f("uq_file_task_id")),
    )
    op.create_index(
        op.f("ix_file_cms_notified"), "file", ["cms_notified"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_cms_notified"), table_name="file")
    op.drop_table("file")
    # ### end Alembic commands ###
