"""rename user to account

Revision ID: 3d5b282d74cf
Revises: 71540af307df
Create Date: 2026-04-03 10:24:37.410642

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d5b282d74cf"
down_revision = "71540af307df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all indices on the user table
    op.drop_index("ix_user_idp_sub", table_name="user")
    op.drop_index("ix_user_username", table_name="user")
    # Drop constraints and rename columns against other tables
    # - SshKeys
    op.drop_constraint("fk_sshkey_user_id_user", "sshkey", type_="foreignkey")
    op.alter_column("sshkey", "user_id", new_column_name="account_id")

    # - RefreshToken
    op.drop_index("ix_refresh_token_user_id", table_name="refresh_token")
    op.drop_constraint(
        "fk_refresh_token_user_id_user", "refresh_token", type_="foreignkey"
    )
    op.alter_column("refresh_token", "user_id", new_column_name="account_id")

    # - Worker
    op.drop_constraint("fk_worker_user_id_user", "worker", type_="foreignkey")
    op.alter_column("worker", "user_id", new_column_name="account_id")

    # - RequestedTask
    op.drop_constraint(
        "fk_requested_task_requested_by_id_user", "requested_task", type_="foreignkey"
    )

    # - Task
    op.drop_constraint("fk_task_requested_by_id_user", "task", type_="foreignkey")
    op.drop_constraint("fk_task_canceled_by_id_user", "task", type_="foreignkey")

    # - RecipeHistory
    op.drop_constraint(
        "fk_recipe_history_author_id_user", "recipe_history", type_="foreignkey"
    )

    # Rename the table from user to account and recreate the indices
    op.rename_table("user", "account")
    # Rename the primary key constraint to match the new table name
    op.execute("ALTER TABLE account RENAME CONSTRAINT pk_user TO pk_account")
    op.create_index(op.f("ix_account_idp_sub"), "account", ["idp_sub"], unique=True)
    op.create_index(op.f("ix_account_username"), "account", ["username"], unique=True)
    op.create_index(
        "ix_refresh_token_account_id",
        table_name="refresh_token",
        columns=["account_id", "token"],
        unique=True,
    )

    # Recreate the inbound foreign key constraints to account
    op.create_foreign_key(
        op.f("fk_recipe_history_author_id_account"),
        "recipe_history",
        "account",
        ["author_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_refresh_token_account_id_account"),
        "refresh_token",
        "account",
        ["account_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_requested_task_requested_by_id_account"),
        "requested_task",
        "account",
        ["requested_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_sshkey_account_id_account"),
        "sshkey",
        "account",
        ["account_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_task_requested_by_id_account"),
        "task",
        "account",
        ["requested_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_task_canceled_by_id_account"),
        "task",
        "account",
        ["canceled_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_worker_account_id_account"),
        "worker",
        "account",
        ["account_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all foreign keys pointing to account table
    op.drop_constraint(
        op.f("fk_worker_account_id_account"), "worker", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_task_canceled_by_id_account"), "task", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_task_requested_by_id_account"), "task", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_sshkey_account_id_account"), "sshkey", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_requested_task_requested_by_id_account"),
        "requested_task",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_refresh_token_account_id_account"),
        "refresh_token",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_recipe_history_author_id_account"),
        "recipe_history",
        type_="foreignkey",
    )

    op.drop_index("ix_refresh_token_account_id", table_name="refresh_token")
    op.drop_index(op.f("ix_account_username"), table_name="account")
    op.drop_index(op.f("ix_account_idp_sub"), table_name="account")

    op.execute("ALTER TABLE account RENAME CONSTRAINT pk_account TO pk_user")

    op.rename_table("account", "user")

    # Recreate foreign keys to user table
    op.create_foreign_key(
        "fk_recipe_history_author_id_user",
        "recipe_history",
        "user",
        ["author_id"],
        ["id"],
    )

    op.create_foreign_key(
        "fk_task_canceled_by_id_user", "task", "user", ["canceled_by_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_task_requested_by_id_user", "task", "user", ["requested_by_id"], ["id"]
    )

    op.create_foreign_key(
        "fk_requested_task_requested_by_id_user",
        "requested_task",
        "user",
        ["requested_by_id"],
        ["id"],
    )
    op.alter_column("worker", "account_id", new_column_name="user_id")
    op.create_foreign_key(
        "fk_worker_user_id_user", "worker", "user", ["user_id"], ["id"]
    )

    op.alter_column("refresh_token", "account_id", new_column_name="user_id")
    op.create_foreign_key(
        "fk_refresh_token_user_id_user",
        "refresh_token",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_index(
        "ix_refresh_token_user_id", "refresh_token", ["user_id", "token"], unique=True
    )

    op.alter_column("sshkey", "account_id", new_column_name="user_id")
    op.create_foreign_key(
        "fk_sshkey_user_id_user", "sshkey", "user", ["user_id"], ["id"]
    )

    op.create_index("ix_user_username", "user", ["username"], unique=True)
    op.create_index("ix_user_idp_sub", "user", ["idp_sub"], unique=True)
    # ### end Alembic commands ##
