"""add scheduling_disabled to worker

Revision ID: 3e0b9c118f6e
Revises: d4faac9108d5
Create Date: 2025-10-08 10:44:34.931123

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e0b9c118f6e"
down_revision = "d4faac9108d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker",
        sa.Column(
            "cordoned",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "worker",
        sa.Column(
            "admin_disabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker", "cordoned")
    op.drop_column("worker", "admin_disabled")
    # ### end Alembic commands ###
