"""add ci_secret_has to offliner

Revision ID: 3e43525210c1
Revises: 59de2c4dbaf0
Create Date: 2025-10-02 17:30:21.496250

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e43525210c1"
down_revision = "59de2c4dbaf0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offliner", sa.Column("ci_secret_hash", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offliner", "ci_secret_hash")
    # ### end Alembic commands ###
