"""add_original_schedule_name

Revision ID: 43f385b318d4
Revises: 15354d56545a
Create Date: 2023-09-26 07:56:45.008277

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43f385b318d4"
down_revision = "15354d56545a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # add original_schedule_name as nullable
    op.add_column(
        "requested_task",
        sa.Column("original_schedule_name", sa.String(), nullable=True),
    )

    # populate original_schedule_name from the related schedule (or '<unknown>')
    op.execute(
        """
            UPDATE requested_task
            SET original_schedule_name = COALESCE(
                (SELECT name
                 FROM schedule WHERE
                 schedule.id = requested_task.schedule_id
                ),
                '<unknown>'
            )
        """
    )

    # set original_schedule_name as not nullable
    op.alter_column("requested_task", "original_schedule_name", nullable=False)

    # add original_schedule_name as nullable
    op.add_column(
        "task", sa.Column("original_schedule_name", sa.String(), nullable=True)
    )

    # populate original_schedule_name from the related schedule (or '<unknown>')
    op.execute(
        """
        UPDATE task
        SET original_schedule_name = COALESCE(
            (SELECT name FROM schedule WHERE schedule.id = task.schedule_id),
            '<unknown>'
        )
        """
    )

    # set original_schedule_name as not nullable
    op.alter_column("task", "original_schedule_name", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "original_schedule_name")
    op.drop_column("requested_task", "original_schedule_name")
    # ### end Alembic commands ###
