"""add_original_schedule_name

Revision ID: 43f385b318d4
Revises: 15354d56545a
Create Date: 2023-09-26 07:56:45.008277

"""

import sqlalchemy as sa
from alembic import op

from db.models import RequestedTask, Schedule, Task

# revision identifiers, used by Alembic.
revision = "43f385b318d4"
down_revision = "15354d56545a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # add original_schedule_name as nullable
    op.add_column(
        "requested_task",
        sa.Column("original_schedule_name", sa.String(), nullable=True),
    )

    # set original_schedule_name for requested tasks with existing schedule
    session.execute(
        sa.update(RequestedTask)
        .where(RequestedTask.schedule_id != None)  # noqa: E711
        .values(
            original_schedule_name=sa.select(Schedule.name)
            .where(Schedule.id == RequestedTask.schedule_id)
            .scalar_subquery()
        )
    )

    # set original_schedule_name for requested tasks without existing schedule
    session.execute(
        sa.update(RequestedTask)
        .where(RequestedTask.schedule_id == None)  # noqa: E711
        .values(original_schedule_name="<unknown>")
    )

    # set original_schedule_name as not nullable
    op.alter_column("requested_task", "original_schedule_name", nullable=False)

    # add original_schedule_name as nullable
    op.add_column(
        "task", sa.Column("original_schedule_name", sa.String(), nullable=True)
    )

    # set original_schedule_name for requested tasks with existing schedule
    session.execute(
        sa.update(Task)
        .where(Task.schedule_id != None)  # noqa: E711
        .values(
            original_schedule_name=sa.select(Schedule.name)
            .where(Schedule.id == Task.schedule_id)
            .scalar_subquery()
        )
    )

    # set original_schedule_name for requested tasks without existing schedule
    session.execute(
        sa.update(Task)
        .where(Task.schedule_id == None)  # noqa: E711
        .values(original_schedule_name="<unknown>")
    )

    # set original_schedule_name as not nullable
    op.alter_column("task", "original_schedule_name", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "original_schedule_name")
    op.drop_column("requested_task", "original_schedule_name")
    # ### end Alembic commands ###
