"""set task_file_fk to cascade

Revision ID: 4488f5e8cc58
Revises: fddc3fbad602
Create Date: 2026-04-07 12:55:13.972293

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4488f5e8cc58"
down_revision = "fddc3fbad602"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_file_task_id_task", "file", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_file_task_id_task"),
        "file",
        "task",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_file_task_id_task"), "file", type_="foreignkey")
    op.create_foreign_key("fk_file_task_id_task", "file", "task", ["task_id"], ["id"])
    # ### end Alembic commands ###
