"""Create some indexes

Revision ID: 4de2adfc3d11
Revises: d13a178652d5
Create Date: 2023-04-06 05:13:40.448095

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4de2adfc3d11"
down_revision = "d13a178652d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_refresh_token_user_id"),
        "refresh_token",
        ["user_id", "token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_sshkey_fingerprint"), "sshkey", ["fingerprint"], unique=False
    )
    op.drop_constraint("uq_user_username", "user", type_="unique")
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_unique_constraint("uq_user_username", "user", ["username"])
    op.drop_index(op.f("ix_sshkey_fingerprint"), table_name="sshkey")
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    # ### end Alembic commands ###
