"""add is_valid flag to schedule

Revision ID: 5591af334874
Revises: ceae21f592b7
Create Date: 2025-08-22 13:26:23.400171

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5591af334874"
down_revision = "e607d9722ef4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "is_valid", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "is_valid")
