"""remove ssh_key pkcs8_key column

Revision ID: 59de2c4dbaf0
Revises: 0607dff50f80
Create Date: 2025-10-02 12:04:00.660956

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "59de2c4dbaf0"
down_revision = "0607dff50f80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sshkey", "pkcs8_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sshkey",
        sa.Column("pkcs8_key", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
