"""nullable-shedule-id-on-task

Revision ID: 6970d8681400
Revises: acf1446fa2aa
Create Date: 2023-05-18 10:53:05.286686

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6970d8681400"
down_revision = "acf1446fa2aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "schedule_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "schedule_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
