"""add idp_sub column to user

Revision ID: 6dcfce58220a
Revises: 8b0210f9d9ab
Create Date: 2025-11-18 10:16:17.353670

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = "6dcfce58220a"
down_revision = "c6f29d8b0d04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("idp_sub", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_user_idp_sub"), "user", ["idp_sub"], unique=True)
    op.add_column(
        "requested_task", sa.Column("requested_by_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_requested_task_requested_by_id_user"),
        "requested_task",
        "user",
        ["requested_by_id"],
        ["id"],
    )
    op.add_column("schedule_history", sa.Column("author_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_schedule_history_author_id_user"),
        "schedule_history",
        "user",
        ["author_id"],
        ["id"],
    )
    op.add_column("task", sa.Column("requested_by_id", sa.Uuid(), nullable=True))
    op.add_column("task", sa.Column("canceled_by_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_task_requested_by_id_user"),
        "task",
        "user",
        ["requested_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_task_canceled_by_id_user"), "task", "user", ["canceled_by_id"], ["id"]
    )

    bind = op.get_bind()
    session = Session(bind=bind)

    # Create system users without passwords
    system_usernames = [
        "maint-scripts",
        "periodic-tasks",
        "periodic-task-gone",
        "period-scheduler",
    ]
    for username in system_usernames:
        session.execute(
            sa.text(
                """
                INSERT INTO "user" (username, password_hash, email, role, deleted)
                VALUES (:username, NULL, NULL, 'custom', FALSE)
                ON CONFLICT (username) DO NOTHING
                """
            ),
            {"username": username},
        )

    session.execute(
        sa.text(
            """
            UPDATE schedule_history
            SET author = 'maint-scripts'
            WHERE author = 'admin'
            """
        )
    )

    # Populate UUID columns by looking up usernames in user table

    # For task.requested_by
    session.execute(
        sa.text(
            """
            UPDATE task
            SET requested_by_id = "user".id
            FROM "user"
            WHERE task.requested_by = "user".username
            """
        )
    )

    # For task.canceled_by
    session.execute(
        sa.text(
            """
            UPDATE task
            SET canceled_by_id = "user".id
            FROM "user"
            WHERE task.canceled_by = "user".username
            """
        )
    )

    # For requested_task.requested_by
    session.execute(
        sa.text(
            """
            UPDATE requested_task
            SET requested_by_id = "user".id
            FROM "user"
            WHERE requested_task.requested_by = "user".username
            """
        )
    )

    # For schedule_history.author
    session.execute(
        sa.text(
            """
            UPDATE schedule_history
            SET author_id = "user".id
            FROM "user"
            WHERE schedule_history.author = "user".username
            """
        )
    )

    # Drop old columns
    op.drop_column("task", "requested_by")
    op.drop_column("task", "canceled_by")
    op.drop_column("requested_task", "requested_by")
    op.drop_column("schedule_history", "author")

    # Set NOT NULL constraints where appropriate
    op.alter_column("task", "requested_by_id", nullable=False)
    op.alter_column("requested_task", "requested_by_id", nullable=False)
    op.alter_column("schedule_history", "author_id", nullable=False)


def downgrade() -> None:
    op.add_column(
        "task",
        sa.Column("requested_by", sa.VARCHAR(), nullable=True, autoincrement=False),
    )
    op.add_column(
        "task",
        sa.Column("canceled_by", sa.VARCHAR(), nullable=True, autoincrement=False),
    )
    op.add_column(
        "requested_task",
        sa.Column("requested_by", sa.VARCHAR(), nullable=True, autoincrement=False),
    )
    op.add_column(
        "schedule_history",
        sa.Column("author", sa.VARCHAR(), nullable=True, autoincrement=False),
    )

    bind = op.get_bind()
    session = Session(bind=bind)

    # For task.requested_by
    session.execute(
        sa.text(
            """
            UPDATE task
            SET requested_by = "user".username
            FROM "user"
            WHERE task.requested_by_id = "user".id
            """
        )
    )

    # For task.canceled_by
    session.execute(
        sa.text(
            """
            UPDATE task
            SET canceled_by = "user".username
            FROM "user"
            WHERE task.canceled_by_id = "user".id
            """
        )
    )

    # For requested_task.requested_by
    session.execute(
        sa.text(
            """
            UPDATE requested_task
            SET requested_by = "user".username
            FROM "user"
            WHERE requested_task.requested_by_id = "user".id
            """
        )
    )

    # For schedule_history.author_id
    session.execute(
        sa.text(
            """
            UPDATE schedule_history
            SET author = "user".username
            FROM "user"
            WHERE schedule_history.author_id = "user".id
            """
        )
    )

    op.drop_constraint(op.f("fk_task_canceled_by_id_user"), "task", type_="foreignkey")
    op.drop_constraint(op.f("fk_task_requested_by_id_user"), "task", type_="foreignkey")
    op.drop_column("task", "canceled_by_id")
    op.drop_column("task", "requested_by_id")
    op.drop_constraint(
        op.f("fk_schedule_history_author_id_user"),
        "schedule_history",
        type_="foreignkey",
    )
    op.drop_column("schedule_history", "author_id")
    op.drop_constraint(
        op.f("fk_requested_task_requested_by_id_user"),
        "requested_task",
        type_="foreignkey",
    )
    op.drop_column("requested_task", "requested_by_id")

    # Set NOT NULL constraints where appropriate
    op.alter_column("task", "requested_by", nullable=False)
    op.alter_column("requested_task", "requested_by", nullable=False)
    op.alter_column("schedule_history", "author", nullable=False)

    op.drop_index(op.f("ix_user_idp_sub"), table_name="user")
    op.drop_column("user", "idp_sub")
    # Delete system users created in upgrade
    system_usernames = [
        "maint-scripts",
        "periodic-tasks",
        "periodic-task-gone",
        "period-scheduler",
    ]
    session.execute(
        sa.text(
            """
            DELETE FROM "user"
            WHERE username IN :usernames
            """
        ).bindparams(sa.bindparam("usernames", expanding=True)),
        {"usernames": tuple(system_usernames)},
    )
