"""add idp_sub column to user

Revision ID: 6dcfce58220a
Revises: b298a5831211
Create Date: 2025-11-18 10:16:17.353670

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6dcfce58220a"
down_revision = "8b0210f9d9ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("idp_sub", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_user_idp_sub"), "user", ["idp_sub"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_idp_sub"), table_name="user")
    op.drop_column("user", "idp_sub")
    # ### end Alembic commands ###
