"""rename schedule to recipe

Revision ID: 71540af307df
Revises: cae8fbe62fe8
Create Date: 2026-03-24 09:27:47.346666

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "71540af307df"
down_revision = "cae8fbe62fe8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all indices on the schedule table
    op.drop_index("ix_schedule_name", table_name="schedule")
    op.drop_index("ix_schedule_category", table_name="schedule")
    op.drop_index("ix_schedule_language_code", table_name="schedule")
    op.drop_index("ix_schedule_context", table_name="schedule")
    op.drop_index(
        "ix_schedule_similarity_data", table_name="schedule", postgresql_using="gin"
    )
    op.drop_index("ix_schedule_tags", table_name="schedule")

    # Drop constraints and rename columns against other tables
    # - Tasks
    op.drop_constraint("fk_task_schedule_id_schedule", "task", type_="foreignkey")
    op.alter_column(
        "task", "original_schedule_name", new_column_name="original_recipe_name"
    )
    op.alter_column("task", "schedule_id", new_column_name="recipe_id")

    # - ScheduleHistory -> RecipeHistory
    op.drop_constraint(
        "fk_schedule_history_author_id_user", "schedule_history", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_schedule_history_schedule_id_schedule",
        "schedule_history",
        type_="foreignkey",
    )
    op.alter_column("schedule_history", "schedule_id", new_column_name="recipe_id")
    op.rename_table("schedule_history", "recipe_history")
    # Rename the primary key constraint to match the new table name
    op.execute(
        "ALTER TABLE recipe_history RENAME CONSTRAINT"
        " pk_schedule_history TO pk_recipe_history"
    )

    # - ScheduleDuration -> RecipeDuration
    op.drop_constraint(
        "fk_schedule_duration_worker_id_worker",
        "schedule_duration",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_schedule_duration_schedule_id_schedule",
        "schedule_duration",
        type_="foreignkey",
    )
    op.drop_constraint(
        "uq_schedule_duration_schedule_id", "schedule_duration", type_="unique"
    )
    op.alter_column("schedule_duration", "schedule_id", new_column_name="recipe_id")
    op.rename_table("schedule_duration", "recipe_duration")
    # Rename the primary key constraint to match the new table name
    op.execute(
        "ALTER TABLE recipe_duration RENAME CONSTRAINT"
        " pk_schedule_duration TO pk_recipe_duration"
    )
    op.create_unique_constraint(
        op.f("uq_recipe_duration_recipe_id"),
        "recipe_duration",
        columns=["recipe_id", "worker_id"],
    )

    # - RequestedTask
    op.alter_column(
        "requested_task",
        "original_schedule_name",
        new_column_name="original_recipe_name",
    )
    op.drop_constraint(
        "fk_requested_task_schedule_id_schedule", "requested_task", type_="foreignkey"
    )
    op.drop_constraint(
        "uq_requested_task_schedule_id", "requested_task", type_="unique"
    )
    op.alter_column("requested_task", "schedule_id", new_column_name="recipe_id")
    op.create_unique_constraint(
        op.f("uq_requested_task_recipe_id"), "requested_task", columns=["recipe_id"]
    )

    # - Blob
    op.drop_constraint("fk_blob_schedule_id_schedule", "blob", type_="foreignkey")
    op.drop_constraint("uq_blob_schedule_id", "blob", type_="unique")
    op.alter_column("blob", "schedule_id", new_column_name="recipe_id")
    op.create_unique_constraint(
        op.f("uq_blob_recipe_id"), "blob", ["recipe_id", "flag_name", "checksum"]
    )

    op.drop_constraint(
        "fk_schedule_most_recent_task_id_task", "schedule", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_schedule_offliner_definition_id_offliner_definition",
        "schedule",
        type_="foreignkey",
    )

    # Rename the table from schedule to recipe and recreate the indices
    op.rename_table("schedule", "recipe")
    # Rename the primary key constraint to match the new table name
    op.execute("ALTER TABLE recipe RENAME CONSTRAINT pk_schedule TO pk_recipe")
    op.create_index(op.f("ix_recipe_name"), "recipe", ["name"], unique=True)
    op.create_index(op.f("ix_recipe_category"), "recipe", ["category"], unique=False)
    op.create_index(
        op.f("ix_recipe_language_code"), "recipe", ["language_code"], unique=False
    )
    op.create_index(op.f("ix_recipe_context"), "recipe", ["context"], unique=False)
    op.create_index(
        op.f("ix_recipe_similarity_data"),
        "recipe",
        ["similarity_data"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_recipe_tags"), "recipe", ["tags"], unique=False)

    # Recreate the inbound foreign key constraints pointing to recipe
    op.create_foreign_key(
        op.f("fk_blob_recipe_id_recipe"),
        "blob",
        "recipe",
        ["recipe_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_requested_task_recipe_id_recipe"),
        "requested_task",
        "recipe",
        ["recipe_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_task_recipe_id_recipe"), "task", "recipe", ["recipe_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_recipe_history_recipe_id_recipe"),
        "recipe_history",
        "recipe",
        ["recipe_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_recipe_duration_recipe_id_recipe"),
        "recipe_duration",
        "recipe",
        ["recipe_id"],
        ["id"],
    )

    op.create_foreign_key(
        op.f("fk_recipe_most_recent_task_id_task"),
        "recipe",
        "task",
        ["most_recent_task_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_recipe_offliner_definition_id_offliner_definition"),
        "recipe",
        "offliner_definition",
        ["offliner_definition_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_recipe_duration_worker_id_worker"),
        "recipe_duration",
        "worker",
        ["worker_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_recipe_history_author_id_user"),
        "recipe_history",
        "user",
        ["author_id"],
        ["id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop the outbound FKs on the renamed tables first (added in upgrade), before
    # any table renames, so the constraint names are still resolvable
    op.drop_constraint(
        op.f("fk_recipe_history_author_id_user"), "recipe_history", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_recipe_duration_worker_id_worker"),
        "recipe_duration",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_recipe_offliner_definition_id_offliner_definition"),
        "recipe",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_recipe_most_recent_task_id_task"), "recipe", type_="foreignkey"
    )

    # Drop the inbound foreign key constraints pointing to recipe
    op.drop_constraint(
        op.f("fk_recipe_duration_recipe_id_recipe"),
        "recipe_duration",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_recipe_history_recipe_id_recipe"), "recipe_history", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_task_recipe_id_recipe"), "task", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_requested_task_recipe_id_recipe"), "requested_task", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_blob_recipe_id_recipe"), "blob", type_="foreignkey")

    # Drop the new indices on recipe table
    op.drop_index(op.f("ix_recipe_tags"), table_name="recipe")
    op.drop_index(
        op.f("ix_recipe_similarity_data"), table_name="recipe", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_recipe_context"), table_name="recipe")
    op.drop_index(op.f("ix_recipe_language_code"), table_name="recipe")
    op.drop_index(op.f("ix_recipe_category"), table_name="recipe")
    op.drop_index(op.f("ix_recipe_name"), table_name="recipe")

    # Rename the table back to schedule
    op.rename_table("recipe", "schedule")
    op.execute("ALTER TABLE schedule RENAME CONSTRAINT pk_recipe TO pk_schedule")

    # - Blob (Revert columns and constraints)
    op.drop_constraint(op.f("uq_blob_recipe_id"), "blob", type_="unique")
    op.alter_column("blob", "recipe_id", new_column_name="schedule_id")
    op.create_unique_constraint(
        "uq_blob_schedule_id", "blob", ["schedule_id", "flag_name", "checksum"]
    )
    op.create_foreign_key(
        "fk_blob_schedule_id_schedule",
        "blob",
        "schedule",
        ["schedule_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # - RequestedTask (Revert columns and constraints)
    op.drop_constraint(
        op.f("uq_requested_task_recipe_id"), "requested_task", type_="unique"
    )
    op.alter_column("requested_task", "recipe_id", new_column_name="schedule_id")
    op.alter_column(
        "requested_task",
        "original_recipe_name",
        new_column_name="original_schedule_name",
    )
    op.create_unique_constraint(
        "uq_requested_task_schedule_id", "requested_task", ["schedule_id"]
    )
    op.create_foreign_key(
        "fk_requested_task_schedule_id_schedule",
        "requested_task",
        "schedule",
        ["schedule_id"],
        ["id"],
    )

    # - RecipeDuration back to ScheduleDuration
    op.drop_constraint(
        op.f("uq_recipe_duration_recipe_id"), "recipe_duration", type_="unique"
    )
    op.rename_table("recipe_duration", "schedule_duration")
    op.execute(
        "ALTER TABLE schedule_duration RENAME CONSTRAINT"
        " pk_recipe_duration TO pk_schedule_duration"
    )
    op.alter_column("schedule_duration", "recipe_id", new_column_name="schedule_id")
    op.create_unique_constraint(
        "uq_schedule_duration_schedule_id",
        "schedule_duration",
        ["schedule_id", "worker_id"],
    )
    op.create_foreign_key(
        "fk_schedule_duration_schedule_id_schedule",
        "schedule_duration",
        "schedule",
        ["schedule_id"],
        ["id"],
    )

    # - RecipeHistory back to ScheduleHistory
    op.rename_table("recipe_history", "schedule_history")
    op.execute(
        "ALTER TABLE schedule_history RENAME CONSTRAINT"
        " pk_recipe_history TO pk_schedule_history"
    )
    op.alter_column("schedule_history", "recipe_id", new_column_name="schedule_id")
    op.create_foreign_key(
        "fk_schedule_history_schedule_id_schedule",
        "schedule_history",
        "schedule",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # - Tasks
    op.alter_column("task", "recipe_id", new_column_name="schedule_id")
    op.alter_column(
        "task", "original_recipe_name", new_column_name="original_schedule_name"
    )
    op.create_foreign_key(
        "fk_task_schedule_id_schedule", "task", "schedule", ["schedule_id"], ["id"]
    )

    # Recreate the original indices on the schedule table
    op.create_index("ix_schedule_tags", "schedule", ["tags"], unique=False)
    op.create_index(
        "ix_schedule_similarity_data",
        "schedule",
        ["similarity_data"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_schedule_context", "schedule", ["context"], unique=False)
    op.create_index(
        "ix_schedule_language_code", "schedule", ["language_code"], unique=False
    )
    op.create_index("ix_schedule_category", "schedule", ["category"], unique=False)
    op.create_index("ix_schedule_name", "schedule", ["name"], unique=True)

    # Recreate the outbound FKs that were on the renamed tables, now with
    # the original schedule-based constraint names
    op.create_foreign_key(
        "fk_schedule_most_recent_task_id_task",
        "schedule",
        "task",
        ["most_recent_task_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_schedule_offliner_definition_id_offliner_definition",
        "schedule",
        "offliner_definition",
        ["offliner_definition_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_schedule_duration_worker_id_worker",
        "schedule_duration",
        "worker",
        ["worker_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_schedule_history_author_id_user",
        "schedule_history",
        "user",
        ["author_id"],
        ["id"],
    )
