"""Drop task_id in ScheduleDuration

Revision ID: 76a074cc939b
Revises: 0ad2bf164dae
Create Date: 2023-05-04 11:27:30.248671

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76a074cc939b"
down_revision = "0ad2bf164dae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_schedule_duration_task_id_task", "schedule_duration", type_="foreignkey"
    )
    op.drop_column("schedule_duration", "task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule_duration",
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "fk_schedule_duration_task_id_task",
        "schedule_duration",
        "task",
        ["task_id"],
        ["id"],
    )
    # ### end Alembic commands ###
