"""drop recipe category

Revision ID: 79e20075be3a
Revises: 9dd1d2099a75
Create Date: 2026-06-03 14:53:57.672612

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79e20075be3a"
down_revision = "9dd1d2099a75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipe_category"), table_name="recipe")
    op.drop_column("recipe", "category")
    op.drop_column("recipe_history", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_history",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "recipe",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_recipe_category"), "recipe", ["category"], unique=False)
    # ### end Alembic commands ###
