"""add unique schedule_id constraint on requested task

Revision ID: 884cd20f1401
Revises: 1aaef11983e7
Create Date: 2025-09-11 14:45:18.955657

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "884cd20f1401"
down_revision = "1aaef11983e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_requested_task_schedule_id"), "requested_task", ["schedule_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_requested_task_schedule_id"), "requested_task", type_="unique"
    )
    # ### end Alembic commands ###
