"""store offliner definition version in schedule history

Revision ID: 8b0210f9d9ab
Revises: b298a5831211
Create Date: 2025-11-25 09:57:58.062755

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = "8b0210f9d9ab"
down_revision = "b298a5831211"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule_history",
        sa.Column("offliner_definition_version", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###

    # Populate offliner_definition_version for latest schedule_history of each schedule
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        sa.text(
            """
            WITH latest AS (
                SELECT DISTINCT ON (schedule_id)
                    id AS history_id,
                    schedule_id
                FROM schedule_history
                ORDER BY schedule_id, created_at DESC
            )

            UPDATE schedule_history AS sh
            SET offliner_definition_version = od.version
            FROM schedule AS s
            JOIN offliner_definition AS od
                ON s.offliner_definition_id = od.id
            JOIN latest
                ON latest.schedule_id = s.id
            WHERE sh.schedule_id = s.id
            AND sh.id = latest.history_id
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_history", "offliner_definition_version")
    # ### end Alembic commands ###
