"""add similarity_data to schedules

Revision ID: 944f6039f602
Revises: 3e0b9c118f6e
Create Date: 2025-10-10 13:38:40.907643

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "944f6039f602"
down_revision = "3e0b9c118f6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "similarity_data",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_schedule_similarity_data"),
        "schedule",
        ["similarity_data"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedule_similarity_data"), table_name="schedule")
    op.drop_column("schedule", "similarity_data")
    # ### end Alembic commands ###
