"""add blob content to database

Revision ID: 9dd1d2099a75
Revises: 83a841b3ca2b
Create Date: 2026-04-17 14:12:39.630368

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9dd1d2099a75"
down_revision = "83a841b3ca2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blob", "url", nullable=True)
    op.add_column("blob", sa.Column("content", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blob", "url", nullable=False)
    op.drop_column("blob", "content")
    # ### end Alembic commands ###
