"""add check_filename to files

Revision ID: b02bf91a0376
Revises: 33aea27bb96e
Create Date: 2025-11-10 18:41:05.196236

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b02bf91a0376"
down_revision = "33aea27bb96e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("check_filename", sa.String(), nullable=True))
    op.add_column(
        "file", sa.Column("check_upload_timestamp", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "check_filename")
    op.drop_column("file", "check_upload_timestamp")
    # ### end Alembic commands ###
