"""add display_name field for users

Revision ID: b97643d802d2
Revises: 0da404081fdf
Create Date: 2026-02-26 11:57:30.741174

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = "b97643d802d2"
down_revision = "0da404081fdf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    # First, make the display_name column nullable and populate with entries
    # the column table (which was previously non-nullable)
    op.add_column("user", sa.Column("display_name", sa.String(), nullable=True))
    session.execute(
        sa.text(
            """
            UPDATE "user"
            SET display_name = "user".username
            """
        )
    )
    op.alter_column("user", "username", existing_type=sa.VARCHAR(), nullable=True)
    # Set the display_name column to be non-nullable
    op.alter_column("user", "display_name", existing_type=sa.VARCHAR, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "display_name")
    # ### end Alembic commands ###
