"""add notification to schedule history

Revision ID: c6f29d8b0d04
Revises: 33aa007735da
Create Date: 2026-01-16 12:37:39.876465

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c6f29d8b0d04"
down_revision = "33aa007735da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule_history",
        sa.Column(
            "notification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_history", "notification")
    # ### end Alembic commands ###
