"""add docker image details to worker

Revision ID: cae8fbe62fe8
Revises: b97643d802d2
Create Date: 2026-03-19 07:43:54.418978

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cae8fbe62fe8"
down_revision = "b97643d802d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker", sa.Column("docker_image_hash", sa.String(), nullable=True))
    op.add_column(
        "worker", sa.Column("docker_image_created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker", "docker_image_created_at")
    op.drop_column("worker", "docker_image_hash")
    # ### end Alembic commands ###
