"""add archive status to schedules

Revision ID: d56f0cb3b772
Revises: 3e43525210c1
Create Date: 2025-10-03 12:07:07.674935

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d56f0cb3b772"
down_revision = "3e43525210c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "schedule_history",
        sa.Column(
            "archived", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "archived")
    op.drop_column("schedule_history", "archived")
    # ### end Alembic commands ###
