"""add blob table

Revision ID: e05f7a3a524d
Revises: 8b0210f9d9ab
Create Date: 2025-12-11 08:45:32.777359

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e05f7a3a524d"
down_revision = "8b0210f9d9ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blob",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("flag_name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedule.id"],
            name=op.f("fk_blob_schedule_id_schedule"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blob")),
        sa.UniqueConstraint(
            "schedule_id", "flag_name", "checksum", name=op.f("uq_blob_schedule_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blob")
    # ### end Alembic commands ###
