"""Set fields as non-nullable

Revision ID: e1d3894be9ea
Revises: 0055fc77f5d8
Create Date: 2023-05-04 14:08:19.014269

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e1d3894be9ea"
down_revision = "0055fc77f5d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "requested_task",
        "notification",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("sshkey", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("sshkey", "fingerprint", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("sshkey", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("sshkey", "key", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "sshkey", "added", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("sshkey", "pkcs8_key", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "task",
        "debug",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("task", "requested_by", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "task",
        "container",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "task",
        "notification",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "task",
        "files",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "task",
        "upload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "upload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "task",
        "files",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "task",
        "notification",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "task",
        "container",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("task", "requested_by", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "task",
        "debug",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("sshkey", "pkcs8_key", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "sshkey", "added", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("sshkey", "key", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("sshkey", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("sshkey", "fingerprint", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("sshkey", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "requested_task",
        "notification",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
