"""use language codes for schedules

Revision ID: e607d9722ef4
Revises: ceae21f592b7
Create Date: 2025-08-25 10:15:36.976520

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e607d9722ef4"
down_revision = "7004594a4d69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "language_name_native")
    op.drop_column("schedule", "language_name_en")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column(
            "language_name_en",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    op.add_column(
        "schedule",
        sa.Column(
            "language_name_native",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###
