"""unique worker-to-account association

Revision ID: e8556436e74a
Revises: 4488f5e8cc58
Create Date: 2026-04-08 11:13:34.516307

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e8556436e74a"
down_revision = "4488f5e8cc58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_worker_account_id"), "worker", ["account_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_worker_account_id"), "worker", type_="unique")
    # ### end Alembic commands ###
