"""Add unique constraint on schedule duration

Revision ID: 0055fc77f5d8
Revises: 76a074cc939b
Create Date: 2023-05-04 12:36:14.802432

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0055fc77f5d8"
down_revision = "76a074cc939b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_schedule_duration_schedule_id"),
        "schedule_duration",
        ["schedule_id", "worker_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_schedule_duration_schedule_id"), "schedule_duration", type_="unique"
    )
    # ### end Alembic commands ###
