"""nullable-schedule-id-in-requested-tasks

Revision ID: 3c4d546fde7c
Revises: 6970d8681400
Create Date: 2023-05-18 13:35:13.362937

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c4d546fde7c"
down_revision = "6970d8681400"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "requested_task", "schedule_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "requested_task", "schedule_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
