"""set most_recent_task_id nullable for schedule on delete

Revision ID: 7004594a4d69
Revises: ceae21f592b7
Create Date: 2025-08-26 10:01:25.562172

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "7004594a4d69"
down_revision = "ceae21f592b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_schedule_most_recent_task_id_task", "schedule", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_schedule_most_recent_task_id_task"),
        "schedule",
        "task",
        ["most_recent_task_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_schedule_most_recent_task_id_task"), "schedule", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_schedule_most_recent_task_id_task",
        "schedule",
        "task",
        ["most_recent_task_id"],
        ["id"],
    )
    # ### end Alembic commands ###
