"""Keep deleted users and workers in the database

Revision ID: acf1446fa2aa
Revises: e1d3894be9ea
Create Date: 2023-04-28 11:29:30.878410

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "acf1446fa2aa"
down_revision = "e1d3894be9ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "worker",
        sa.Column(
            "deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker", "deleted")
    op.drop_column("user", "deleted")
    # ### end Alembic commands ###
