"""Store Mongo ID as well

Revision ID: cbedcefd6059
Revises: f1a7eae2c347
Create Date: 2023-04-03 18:01:18.286681

"""
import sqlalchemy as sa
from alembic import op

import db.models as dbm

# revision identifiers, used by Alembic.
revision = "cbedcefd6059"
down_revision = "f1a7eae2c347"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("mongo_id", sa.String(), nullable=True))
    op.create_unique_constraint("user_mongo_id_unq", "user", ["mongo_id"])
    op.execute(
        sa.update(dbm.User).values(mongo_id=dbm.User.mongo_val["_id"]["$oid"].astext)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_mongo_id_unq", "user", type_="unique")
    op.drop_column("user", "mongo_id")
    # ### end Alembic commands ###
