"""Apply a single naming convention

Revision ID: d13a178652d5
Revises: fe65a1b0f953
Create Date: 2023-04-06 04:57:11.449333

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d13a178652d5"
down_revision = "fe65a1b0f953"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_mongo_id_unq", "user", type_="unique")
    op.drop_constraint("username_unq", "user", type_="unique")
    op.create_unique_constraint(op.f("uq_user_mongo_id"), "user", ["mongo_id"])
    op.create_unique_constraint(op.f("uq_user_username"), "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_username"), "user", type_="unique")
    op.drop_constraint(op.f("uq_user_mongo_id"), "user", type_="unique")
    op.create_unique_constraint("username_unq", "user", ["username"])
    op.create_unique_constraint("user_mongo_id_unq", "user", ["mongo_id"])
    # ### end Alembic commands ###
