""" static list of languages supported by zimfarm

    might move to mongo with a proper API should the need to edit this list raise """

import collections

all_languages = collections.OrderedDict(
    sorted(
        {
            "ab": {"name_en": "Abkhazian", "name_native": "Аҧсшәа"},
            "ace": {"name_en": "Achinese", "name_native": "Acèh"},
            "ady": {"name_en": "Adyghe", "name_native": "адыгабзэ"},
            "af": {"name_en": "Afrikaans", "name_native": "Afrikaans"},
            "ak": {"name_en": "Akan", "name_native": "Akan"},
            "als": {"name_en": "Alemannisch", "name_native": "Alemannisch"},
            "am": {"name_en": "Amharic", "name_native": "አማርኛ"},
            "an": {"name_en": "Aragonese", "name_native": "aragonés"},
            "ang": {"name_en": "Old English", "name_native": "Ænglisc"},
            "ar": {"name_en": "Arabic", "name_native": "العربية"},
            "arc": {"name_en": "Aramaic", "name_native": "ܐܪܡܝܐ"},
            "arz": {"name_en": "Egyptian Arabic", "name_native": "مصرى"},
            "as": {"name_en": "Assamese", "name_native": "অসমীয়া"},
            "ast": {"name_en": "Asturian", "name_native": "asturianu"},
            "atj": {"name_en": "Atikamekw", "name_native": "Atikamekw"},
            "av": {"name_en": "Avaric", "name_native": "авар"},
            "ay": {"name_en": "Aymara", "name_native": "Aymar aru"},
            "az": {"name_en": "Azerbaijani", "name_native": "azərbaycan"},
            "azb": {"name_en": "Azerbaijani", "name_native": "تۆرکجه"},
            "ba": {"name_en": "Bashkir", "name_native": "башҡортса"},
            "bar": {"name_en": "Bavarian", "name_native": "Boarisch"},
            "bat-smg": {"name_en": "Samogitian", "name_native": "žemaitėška"},
            "bcl": {"name_en": "Central Bikol", "name_native": "Bikol Central"},
            "be": {"name_en": "Belarusian", "name_native": "беларуская"},
            "be-x-old": {
                "name_en": "Belarusian (Taraškievica orthography)",
                "name_native": "беларуская (тарашкевіца)",
            },
            "bg": {"name_en": "Bulgarian", "name_native": "български"},
            "bh": {"name_en": "Bhojpuri", "name_native": "भोजपुरी"},
            "bi": {"name_en": "Bislama", "name_native": "Bislama"},
            "bjn": {"name_en": "Banjar", "name_native": "Bahasa Banjar"},
            "bm": {"name_en": "Bambara", "name_native": "bamanankan"},
            "bn": {"name_en": "Bangla", "name_native": "বাংলা"},
            "bo": {"name_en": "Tibetan", "name_native": "བོད་ཡིག"},
            "bpy": {
                "name_en": "Bishnupriya Manipuri",
                "name_native": "বিষ্ণুপ্রিয়া মণিপুরী",
            },
            "br": {"name_en": "Breton", "name_native": "brezhoneg"},
            "bs": {"name_en": "Bosnian", "name_native": "bosanski"},
            "bug": {"name_en": "Buginese", "name_native": "ᨅᨔ ᨕᨘᨁᨗ"},
            "bxr": {"name_en": "Russia Buriat", "name_native": "буряад"},
            "ca": {"name_en": "Catalan", "name_native": "català"},
            "cbk-zam": {
                "name_en": "Chavacano",
                "name_native": "Chavacano de Zamboanga",
            },
            "cdo": {"name_en": "Min Dong Chinese", "name_native": "Mìng-dĕ̤ng-ngṳ̄"},
            "ce": {"name_en": "Chechen", "name_native": "нохчийн"},
            "ceb": {"name_en": "Cebuano", "name_native": "Cebuano"},
            "ch": {"name_en": "Chamorro", "name_native": "Chamoru"},
            "chr": {"name_en": "Cherokee", "name_native": "ᏣᎳᎩ"},
            "chy": {"name_en": "Cheyenne", "name_native": "Tsetsêhestâhese"},
            "ckb": {"name_en": "Central Kurdish", "name_native": "کوردی"},
            "co": {"name_en": "Corsican", "name_native": "corsu"},
            "cr": {"name_en": "Cree", "name_native": "Nēhiyawēwin / ᓀᐦᐃᔭᐍᐏᐣ"},
            "crh": {"name_en": "Crimean Turkish", "name_native": "qırımtatarca"},
            "cs": {"name_en": "Czech", "name_native": "čeština"},
            "csb": {"name_en": "Kashubian", "name_native": "kaszëbsczi"},
            "cu": {
                "name_en": "Church Slavic",
                "name_native": "словѣньскъ / ⰔⰎⰑⰂⰡⰐⰠⰔⰍⰟ",
            },
            "cv": {"name_en": "Chuvash", "name_native": "Чӑвашла"},
            "cy": {"name_en": "Welsh", "name_native": "Cymraeg"},
            "da": {"name_en": "Danish", "name_native": "dansk"},
            "de": {"name_en": "German", "name_native": "Deutsch"},
            "din": {"name_en": "Dinka", "name_native": "Thuɔŋjäŋ"},
            "diq": {"name_en": "Zazaki", "name_native": "Zazaki"},
            "dsb": {"name_en": "Lower Sorbian", "name_native": "dolnoserbski"},
            "dty": {"name_en": "Doteli", "name_native": "डोटेली"},
            "dv": {"name_en": "Divehi", "name_native": "ދިވެހިބަސް"},
            "dz": {"name_en": "Dzongkha", "name_native": "ཇོང་ཁ"},
            "ee": {"name_en": "Ewe", "name_native": "eʋegbe"},
            "el": {"name_en": "Greek", "name_native": "Ελληνικά"},
            "eml": {
                "name_en": "Emiliano-Romagnolo",
                "name_native": "emiliàn e rumagnòl",
            },
            "en": {"name_en": "English", "name_native": "English"},
            "eo": {"name_en": "Esperanto", "name_native": "esperanto"},
            "es": {"name_en": "Spanish", "name_native": "español"},
            "et": {"name_en": "Estonian", "name_native": "eesti"},
            "eu": {"name_en": "Basque", "name_native": "euskara"},
            "ext": {"name_en": "Extremaduran", "name_native": "estremeñu"},
            "fa": {"name_en": "Persian", "name_native": "فارسی"},
            "ff": {"name_en": "Fulah", "name_native": "Fulfulde"},
            "fi": {"name_en": "Finnish", "name_native": "suomi"},
            "fiu-vro": {"name_en": "Võro", "name_native": "Võro"},
            "fj": {"name_en": "Fijian", "name_native": "Na Vosa Vakaviti"},
            "fo": {"name_en": "Faroese", "name_native": "føroyskt"},
            "fr": {"name_en": "French", "name_native": "français"},
            "frp": {"name_en": "Arpitan", "name_native": "arpetan"},
            "frr": {"name_en": "Northern Frisian", "name_native": "Nordfriisk"},
            "fur": {"name_en": "Friulian", "name_native": "furlan"},
            "fy": {"name_en": "Western Frisian", "name_native": "Frysk"},
            "ga": {"name_en": "Irish", "name_native": "Gaeilge"},
            "gag": {"name_en": "Gagauz", "name_native": "Gagauz"},
            "gan": {"name_en": "Gan Chinese", "name_native": "贛語"},
            "gd": {"name_en": "Scottish Gaelic", "name_native": "Gàidhlig"},
            "gl": {"name_en": "Galician", "name_native": "galego"},
            "glk": {"name_en": "Gilaki", "name_native": "گیلکی"},
            "gn": {"name_en": "Guarani", "name_native": "Avañe'ẽ"},
            "gom": {
                "name_en": "Goan Konkani",
                "name_native": "गोंयची कोंकणी / Gõychi Konknni",
            },
            "gor": {"name_en": "Gorontalo", "name_native": "Bahasa Hulontalo"},
            "got": {"name_en": "Gothic", "name_native": "𐌲𐌿𐍄𐌹𐍃𐌺"},
            "gu": {"name_en": "Gujarati", "name_native": "ગુજરાતી"},
            "gv": {"name_en": "Manx", "name_native": "Gaelg"},
            "ha": {"name_en": "Hausa", "name_native": "Hausa"},
            "hak": {"name_en": "Hakka Chinese", "name_native": "客家語/Hak-kâ-ngî"},
            "haw": {"name_en": "Hawaiian", "name_native": "Hawaiʻi"},
            "he": {"name_en": "Hebrew", "name_native": "עברית"},
            "hi": {"name_en": "Hindi", "name_native": "हिन्दी"},
            "hif": {"name_en": "Fiji Hindi", "name_native": "Fiji Hindi"},
            "hr": {"name_en": "Croatian", "name_native": "hrvatski"},
            "hsb": {"name_en": "Upper Sorbian", "name_native": "hornjoserbsce"},
            "ht": {"name_en": "Haitian Creole", "name_native": "Kreyòl ayisyen"},
            "hu": {"name_en": "Hungarian", "name_native": "magyar"},
            "hy": {"name_en": "Armenian", "name_native": "հայերեն"},
            "ia": {"name_en": "Interlingua", "name_native": "interlingua"},
            "id": {"name_en": "Indonesian", "name_native": "Indonesia"},
            "ie": {"name_en": "Interlingue", "name_native": "Interlingue"},
            "ig": {"name_en": "Igbo", "name_native": "Igbo"},
            "ik": {"name_en": "Inupiaq", "name_native": "Iñupiak"},
            "ilo": {"name_en": "Iloko", "name_native": "Ilokano"},
            "inh": {"name_en": "Ingush", "name_native": "ГӀалгӀай"},
            "io": {"name_en": "Ido", "name_native": "Ido"},
            "is": {"name_en": "Icelandic", "name_native": "íslenska"},
            "it": {"name_en": "Italian", "name_native": "italiano"},
            "iu": {"name_en": "Inuktitut", "name_native": "ᐃᓄᒃᑎᑐᑦ/inuktitut"},
            "ja": {"name_en": "Japanese", "name_native": "日本語"},
            "jam": {"name_en": "Jamaican Creole English", "name_native": "Patois"},
            "jbo": {"name_en": "Lojban", "name_native": "la .lojban."},
            "jv": {"name_en": "Javanese", "name_native": "Basa Jawa"},
            "ka": {"name_en": "Georgian", "name_native": "ქართული"},
            "kaa": {"name_en": "Kara-Kalpak", "name_native": "Qaraqalpaqsha"},
            "kab": {"name_en": "Kabyle", "name_native": "Taqbaylit"},
            "kbd": {"name_en": "Kabardian", "name_native": "Адыгэбзэ"},
            "kbp": {"name_en": "Kabiye", "name_native": "Kabɩyɛ"},
            "kg": {"name_en": "Kongo", "name_native": "Kongo"},
            "ki": {"name_en": "Kikuyu", "name_native": "Gĩkũyũ"},
            "kk": {"name_en": "Kazakh", "name_native": "қазақ тілі"},
            "kl": {"name_en": "Kalaallisut", "name_native": "kalaallisut"},
            "km": {"name_en": "Khmer", "name_native": "ភាសាខ្មែរ"},
            "kn": {"name_en": "Kannada", "name_native": "ಕನ್ನಡ"},
            "ko": {"name_en": "Korean", "name_native": "한국어"},
            "koi": {"name_en": "Komi-Permyak", "name_native": "Перем Коми"},
            "krc": {"name_en": "Karachay-Balkar", "name_native": "къарачай-малкъар"},
            "ks": {"name_en": "Kashmiri", "name_native": "कॉशुर / کٲشُر"},
            "ksh": {"name_en": "Colognian", "name_native": "Ripoarisch"},
            "ku": {"name_en": "Kurdish", "name_native": "kurdî"},
            "kv": {"name_en": "Komi", "name_native": "коми"},
            "kw": {"name_en": "Cornish", "name_native": "kernowek"},
            "ky": {"name_en": "Kyrgyz", "name_native": "Кыргызча"},
            "la": {"name_en": "Latin", "name_native": "Latina"},
            "lad": {"name_en": "Ladino", "name_native": "Ladino"},
            "lb": {"name_en": "Luxembourgish", "name_native": "Lëtzebuergesch"},
            "lbe": {"name_en": "Lak", "name_native": "лакку"},
            "lez": {"name_en": "Lezghian", "name_native": "лезги"},
            "lfn": {
                "name_en": "Lingua Franca Nova",
                "name_native": "Lingua Franca Nova",
            },
            "lg": {"name_en": "Ganda", "name_native": "Luganda"},
            "li": {"name_en": "Limburgish", "name_native": "Limburgs"},
            "lij": {"name_en": "Ligurian", "name_native": "Ligure"},
            "lmo": {"name_en": "Lombard", "name_native": "lumbaart"},
            "ln": {"name_en": "Lingala", "name_native": "lingála"},
            "lo": {"name_en": "Lao", "name_native": "ລາວ"},
            "lrc": {"name_en": "Northern Luri", "name_native": "لۊری شومالی"},
            "lt": {"name_en": "Lithuanian", "name_native": "lietuvių"},
            "ltg": {"name_en": "Latgalian", "name_native": "latgaļu"},
            "lv": {"name_en": "Latvian", "name_native": "latviešu"},
            "mai": {"name_en": "Maithili", "name_native": "मैथिली"},
            "map-bms": {"name_en": "Basa Banyumasan", "name_native": "Basa Banyumasan"},
            "mdf": {"name_en": "Moksha", "name_native": "мокшень"},
            "mg": {"name_en": "Malagasy", "name_native": "Malagasy"},
            "mhr": {"name_en": "Eastern Mari", "name_native": "олык марий"},
            "mi": {"name_en": "Maori", "name_native": "Māori"},
            "min": {"name_en": "Minangkabau", "name_native": "Baso Minangkabau"},
            "mk": {"name_en": "Macedonian", "name_native": "македонски"},
            "ml": {"name_en": "Malayalam", "name_native": "മലയാളം"},
            "mn": {"name_en": "Mongolian", "name_native": "монгол"},
            "mr": {"name_en": "Marathi", "name_native": "मराठी"},
            "mrj": {"name_en": "Western Mari", "name_native": "кырык мары"},
            "ms": {"name_en": "Malay", "name_native": "Melayu"},
            "mt": {"name_en": "Maltese", "name_native": "Malti"},
            "multi": {
                "name_en": "Multiple Languages",
                "name_native": "Multiple Languages",
            },
            "mwl": {"name_en": "Mirandese", "name_native": "Mirandés"},
            "my": {"name_en": "Burmese", "name_native": "မြန်မာဘာသာ"},
            "myv": {"name_en": "Erzya", "name_native": "эрзянь"},
            "mzn": {"name_en": "Mazanderani", "name_native": "مازِرونی"},
            "na": {"name_en": "Nauru", "name_native": "Dorerin Naoero"},
            "nah": {"name_en": "Nāhuatl", "name_native": "Nāhuatl"},
            "nan": {"name_en": "Chinese (Min Nan)", "name_native": "Bân-lâm-gú"},
            "nap": {"name_en": "Neapolitan", "name_native": "Napulitano"},
            "nds": {"name_en": "Low German", "name_native": "Plattdüütsch"},
            "nds-nl": {"name_en": "Low Saxon", "name_native": "Nedersaksies"},
            "ne": {"name_en": "Nepali", "name_native": "नेपाली"},
            "new": {"name_en": "Newari", "name_native": "नेपाल भाषा"},
            "nl": {"name_en": "Dutch", "name_native": "Nederlands"},
            "nn": {"name_en": "Norwegian Nynorsk", "name_native": "nynorsk"},
            "no": {
                "name_en": "Norwegian Bokmål (Norway)",
                "name_native": "norsk bokmål (Norge)",
            },
            "nov": {"name_en": "Novial", "name_native": "Novial"},
            "nrm": {"name_en": "Norman", "name_native": "Nouormand"},
            "nso": {"name_en": "Northern Sotho", "name_native": "Sesotho sa Leboa"},
            "nv": {"name_en": "Navajo", "name_native": "Diné bizaad"},
            "ny": {"name_en": "Nyanja", "name_native": "Chi-Chewa"},
            "oc": {"name_en": "Occitan", "name_native": "occitan"},
            "olo": {"name_en": "Livvi-Karelian", "name_native": "Livvinkarjala"},
            "om": {"name_en": "Oromo", "name_native": "Oromoo"},
            "or": {"name_en": "Odia", "name_native": "ଓଡ଼ିଆ"},
            "os": {"name_en": "Ossetic", "name_native": "Ирон"},
            "pa": {"name_en": "Punjabi", "name_native": "ਪੰਜਾਬੀ"},
            "pag": {"name_en": "Pangasinan", "name_native": "Pangasinan"},
            "pam": {"name_en": "Pampanga", "name_native": "Kapampangan"},
            "pap": {"name_en": "Papiamento", "name_native": "Papiamentu"},
            "pcd": {"name_en": "Picard", "name_native": "Picard"},
            "pdc": {"name_en": "Pennsylvania German", "name_native": "Deitsch"},
            "pfl": {"name_en": "Palatine German", "name_native": "Pälzisch"},
            "pi": {"name_en": "Pali", "name_native": "पालि"},
            "pih": {"name_en": "Norfuk / Pitkern", "name_native": "Norfuk / Pitkern"},
            "pl": {"name_en": "Polish", "name_native": "polski"},
            "pms": {"name_en": "Piedmontese", "name_native": "Piemontèis"},
            "pnb": {"name_en": "Western Punjabi", "name_native": "پنجابی"},
            "pnt": {"name_en": "Pontic", "name_native": "Ποντιακά"},
            "ps": {"name_en": "Pashto", "name_native": "پښتو"},
            "pt": {"name_en": "Portuguese", "name_native": "português"},
            "qu": {"name_en": "Quechua", "name_native": "Runa Simi"},
            "rm": {"name_en": "Romansh", "name_native": "rumantsch"},
            "rmy": {"name_en": "Romani", "name_native": "Romani"},
            "rn": {"name_en": "Rundi", "name_native": "Kirundi"},
            "ro": {"name_en": "Romanian", "name_native": "română"},
            "roa-rup": {"name_en": "Aromanian", "name_native": "armãneashti"},
            "roa-tara": {"name_en": "Tarantino", "name_native": "tarandíne"},
            "ru": {"name_en": "Russian", "name_native": "русский"},
            "rue": {"name_en": "Rusyn", "name_native": "русиньскый"},
            "rw": {"name_en": "Kinyarwanda", "name_native": "Kinyarwanda"},
            "sa": {"name_en": "Sanskrit", "name_native": "संस्कृतम्"},
            "sah": {"name_en": "Sakha", "name_native": "саха тыла"},
            "sat": {"name_en": "Santali", "name_native": "ᱥᱟᱱᱛᱟᱲᱤ"},
            "sc": {"name_en": "Sardinian", "name_native": "sardu"},
            "scn": {"name_en": "Sicilian", "name_native": "sicilianu"},
            "sco": {"name_en": "Scots", "name_native": "Scots"},
            "sd": {"name_en": "Sindhi", "name_native": "سنڌي"},
            "se": {"name_en": "Northern Sami", "name_native": "davvisámegiella"},
            "sg": {"name_en": "Sango", "name_native": "Sängö"},
            "sh": {
                "name_en": "Serbo-Croatian",
                "name_native": "Srpskohrvatski / hrvatskosrpski",
            },
            "shn": {"name_en": "Shan", "name_native": "ၽႃႇသႃႇတႆး "},
            "si": {"name_en": "Sinhala", "name_native": "සිංහල"},
            "simple": {"name_en": "Simple English", "name_native": "Simple English"},
            "sk": {"name_en": "Slovak", "name_native": "slovenčina"},
            "sl": {"name_en": "Slovenian", "name_native": "slovenščina"},
            "sm": {"name_en": "Samoan", "name_native": "Gagana Samoa"},
            "sn": {"name_en": "Shona", "name_native": "chiShona"},
            "so": {"name_en": "Somali", "name_native": "Soomaaliga"},
            "sq": {"name_en": "Albanian", "name_native": "shqip"},
            "sr": {"name_en": "Serbian", "name_native": "српски"},
            "srn": {"name_en": "Sranan Tongo", "name_native": "Sranantongo"},
            "ss": {"name_en": "Swati", "name_native": "SiSwati"},
            "st": {"name_en": "Southern Sotho", "name_native": "Sesotho"},
            "stq": {"name_en": "Saterland Frisian", "name_native": "Seeltersk"},
            "su": {"name_en": "Sundanese", "name_native": "Basa Sunda"},
            "sv": {"name_en": "Swedish", "name_native": "svenska"},
            "sw": {"name_en": "Swahili", "name_native": "Kiswahili"},
            "szl": {"name_en": "Silesian", "name_native": "ślůnski"},
            "ta": {"name_en": "Tamil", "name_native": "தமிழ்"},
            "tcy": {"name_en": "Tulu", "name_native": "ತುಳು"},
            "te": {"name_en": "Telugu", "name_native": "తెలుగు"},
            "tet": {"name_en": "Tetum", "name_native": "tetun"},
            "tg": {"name_en": "Tajik", "name_native": "тоҷикӣ"},
            "th": {"name_en": "Thai", "name_native": "ไทย"},
            "ti": {"name_en": "Tigrinya", "name_native": "ትግርኛ"},
            "tk": {"name_en": "Turkmen", "name_native": "Türkmençe"},
            "tl": {"name_en": "Tagalog", "name_native": "Tagalog"},
            "tn": {"name_en": "Tswana", "name_native": "Setswana"},
            "to": {"name_en": "Tongan", "name_native": "lea faka-Tonga"},
            "tpi": {"name_en": "Tok Pisin", "name_native": "Tok Pisin"},
            "tr": {"name_en": "Turkish", "name_native": "Türkçe"},
            "ts": {"name_en": "Tsonga", "name_native": "Xitsonga"},
            "tt": {"name_en": "Tatar", "name_native": "татарча/tatarça"},
            "tum": {"name_en": "Tumbuka", "name_native": "chiTumbuka"},
            "tw": {"name_en": "Twi", "name_native": "Twi"},
            "ty": {"name_en": "Tahitian", "name_native": "reo tahiti"},
            "tyv": {"name_en": "Tuvinian", "name_native": "тыва дыл"},
            "udm": {"name_en": "Udmurt", "name_native": "удмурт"},
            "ug": {"name_en": "Uyghur", "name_native": "ئۇيغۇرچە / Uyghurche"},
            "uk": {"name_en": "Ukrainian", "name_native": "українська"},
            "ur": {"name_en": "Urdu", "name_native": "اردو"},
            "uz": {"name_en": "Uzbek", "name_native": "o‘zbek"},
            "ve": {"name_en": "Venda", "name_native": "Tshivenda"},
            "vec": {"name_en": "Venetian", "name_native": "vèneto"},
            "vep": {"name_en": "Veps", "name_native": "vepsän kel’"},
            "vi": {"name_en": "Vietnamese", "name_native": "Tiếng Việt"},
            "vls": {"name_en": "West Flemish", "name_native": "West-Vlams"},
            "vo": {"name_en": "Volapük", "name_native": "Volapük"},
            "wa": {"name_en": "Walloon", "name_native": "walon"},
            "war": {"name_en": "War", "name_native": "Winaray"},
            "wo": {"name_en": "Wolof", "name_native": "Wolof"},
            "wuu": {"name_en": "Wu Chinese", "name_native": "吴语"},
            "xal": {"name_en": "Kalmyk", "name_native": "хальмг"},
            "xh": {"name_en": "Xhosa", "name_native": "isiXhosa"},
            "xmf": {"name_en": "Mingrelian", "name_native": "მარგალური"},
            "yi": {"name_en": "Yiddish", "name_native": "ייִדיש"},
            "yo": {"name_en": "Yoruba", "name_native": "Yorùbá"},
            "za": {"name_en": "Zhuang", "name_native": "Vahcuengh"},
            "zea": {"name_en": "Zeelandic", "name_native": "Zeêuws"},
            "zh": {"name_en": "Chinese", "name_native": "中文"},
            "zh-classical": {"name_en": "Classical Chinese", "name_native": "文言"},
            "zh-min-nan": {"name_en": "Chinese (Min Nan)", "name_native": "Bân-lâm-gú"},
            "zh-yue": {"name_en": "Cantonese", "name_native": "粵語"},
            "zu": {"name_en": "Zulu", "name_native": "isiZulu"},
        }.items()
    )
)
