name: Docker

on:
  tags:
    - db-migration

jobs:

  dispatcher:
    name: Deploy dispatcher Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-dispatcher
          restrict-to: openzim/zimfarm
          context: dispatcher/backend
          manual-tag: db-migration
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
