name: Healthcheck Tests

on:
  pull_request:
    paths:
      - "healthcheck/**"
  push:
    paths:
      - "healthcheck/**"
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: healthcheck/pyproject.toml
          architecture: x64

      - name: Build healthcheck Docker image
        working-directory: healthcheck
        run: docker build -t zimfarm-healthcheck:test .

      - name: Run healthcheck container
        run: |
          docker run -d --name zimfarm-healthcheck-test \
            --network host \
            -e ZIMFARM_API_URL=http://localhost:8001 \
            -e ZIMFARM_FRONTEND_URL=http://localhost:8001 \
            -e CMS_API_URL=http://localhost:8001 \
            -e ZIMFARM_USERNAME=admin \
            -e ZIMFARM_PASSWORD=admin_pass \
            -e ZIMFARM_DATABASE_URL=postgresql+psycopg://zimfarm:zimpass@localhost:5432/zimtest \
            -p 8000:80 \
            zimfarm-healthcheck:test
          # wait for container to be ready
          for i in {1..10}; do
            http_code=$(curl -s -o /dev/null -w "%{http_code}" 'http://localhost:80/docs' || echo 0000)
            if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
              echo "Healthcheck API is up!"
              exit 0
            else
              echo "Waiting for healthcheck API... ($i/10)"
              sleep 3
            fi
          done

          echo "Healthcheck API failed to start:"
          docker logs zimfarm-healthcheck-test
          exit 1
