name: Recipesauto QA

on:
  pull_request:
    paths:
      - "recipesauto/**"
  push:
    paths:
      - "recipesauto/**"
    branches:
      - main

jobs:
  check-qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: recipesauto/pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        working-directory: recipesauto
        run: |
          pip install -U pip
          pip install -e .[qa,scripts,test]

      - name: Check Linting
        working-directory: recipesauto
        run: inv check-lint

      - name: Check Formatting
        working-directory: recipesauto
        run: inv check-format

      - name: Check Type
        working-directory: recipesauto
        run: inv check-type
